package xxxt.oracle.apps.xxxt.einvoice.earchive.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EArchiveNotesVORowImpl extends OAViewRowImpl {
    public static final int EINVNOTEID = 0;
    public static final int EINVINVOICEID = 1;
    public static final int NOTE = 2;
    public static final int EINVRESPID = 3;
    public static final int EARCHIVEHEADERVO = 4;

    /**This is the default constructor (do not remove)
     */
    public EArchiveNotesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EinvNoteId
     */
    public Number getEinvNoteId() {
        return (Number) getAttributeInternal(EINVNOTEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EinvNoteId
     */
    public void setEinvNoteId(Number value) {
        setAttributeInternal(EINVNOTEID, value);
    }

    /**Gets the attribute value for the calculated attribute EinvInvoiceId
     */
    public Number getEinvInvoiceId() {
        return (Number) getAttributeInternal(EINVINVOICEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EinvInvoiceId
     */
    public void setEinvInvoiceId(Number value) {
        setAttributeInternal(EINVINVOICEID, value);
    }

    /**Gets the attribute value for the calculated attribute Note
     */
    public String getNote() {
        return (String) getAttributeInternal(NOTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Note
     */
    public void setNote(String value) {
        setAttributeInternal(NOTE, value);
    }

    /**Gets the attribute value for the calculated attribute EinvRespId
     */
    public Number getEinvRespId() {
        return (Number) getAttributeInternal(EINVRESPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EinvRespId
     */
    public void setEinvRespId(Number value) {
        setAttributeInternal(EINVRESPID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EINVNOTEID:
            return getEinvNoteId();
        case EINVINVOICEID:
            return getEinvInvoiceId();
        case NOTE:
            return getNote();
        case EINVRESPID:
            return getEinvRespId();
        case EARCHIVEHEADERVO:
            return getEArchiveHeaderVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EINVNOTEID:
            setEinvNoteId((Number)value);
            return;
        case EINVINVOICEID:
            setEinvInvoiceId((Number)value);
            return;
        case NOTE:
            setNote((String)value);
            return;
        case EINVRESPID:
            setEinvRespId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>Row</code> using master-detail link EArchiveHeaderVO
     */
    public Row getEArchiveHeaderVO() {
        return (Row)getAttributeInternal(EARCHIVEHEADERVO);
    }
}
