package xxxt.oracle.apps.xxxt.einvoice.earchive.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EArchiveSearchPanelVORowImpl extends OAViewRowImpl {
    public static final int EARSIVNO = 0;
    public static final int TCKNVKN = 1;
    public static final int FIRMAADI = 2;
    public static final int FATURATARIHIBASLANGIC = 3;
    public static final int FATURATARIHIBITIS = 4;
    public static final int STATUS = 5;
    public static final int FATURAGONDERIMBASLANGIC = 6;
    public static final int FATURAGONDERIMBITIS = 7;
    public static final int SOURCE = 8;

    /**This is the default constructor (do not remove)
     */
    public EArchiveSearchPanelVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EArsivNo
     */
    public String getEArsivNo() {
        return (String) getAttributeInternal(EARSIVNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EArsivNo
     */
    public void setEArsivNo(String value) {
        setAttributeInternal(EARSIVNO, value);
    }

    /**Gets the attribute value for the calculated attribute TcknVkn
     */
    public String getTcknVkn() {
        return (String) getAttributeInternal(TCKNVKN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TcknVkn
     */
    public void setTcknVkn(String value) {
        setAttributeInternal(TCKNVKN, value);
    }

    /**Gets the attribute value for the calculated attribute FirmaAdi
     */
    public String getFirmaAdi() {
        return (String) getAttributeInternal(FIRMAADI);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FirmaAdi
     */
    public void setFirmaAdi(String value) {
        setAttributeInternal(FIRMAADI, value);
    }

    /**Gets the attribute value for the calculated attribute FaturaTarihiBaslangic
     */
    public Date getFaturaTarihiBaslangic() {
        return (Date) getAttributeInternal(FATURATARIHIBASLANGIC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaturaTarihiBaslangic
     */
    public void setFaturaTarihiBaslangic(Date value) {
        setAttributeInternal(FATURATARIHIBASLANGIC, value);
    }

    /**Gets the attribute value for the calculated attribute FaturaTarihiBitis
     */
    public Date getFaturaTarihiBitis() {
        return (Date) getAttributeInternal(FATURATARIHIBITIS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaturaTarihiBitis
     */
    public void setFaturaTarihiBitis(Date value) {
        setAttributeInternal(FATURATARIHIBITIS, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute FaturaGonderimBaslangic
     */
    public Date getFaturaGonderimBaslangic() {
        return (Date) getAttributeInternal(FATURAGONDERIMBASLANGIC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaturaGonderimBaslangic
     */
    public void setFaturaGonderimBaslangic(Date value) {
        setAttributeInternal(FATURAGONDERIMBASLANGIC, value);
    }

    /**Gets the attribute value for the calculated attribute FaturaGonderimBitis
     */
    public Date getFaturaGonderimBitis() {
        return (Date) getAttributeInternal(FATURAGONDERIMBITIS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FaturaGonderimBitis
     */
    public void setFaturaGonderimBitis(Date value) {
        setAttributeInternal(FATURAGONDERIMBITIS, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EARSIVNO:
            return getEArsivNo();
        case TCKNVKN:
            return getTcknVkn();
        case FIRMAADI:
            return getFirmaAdi();
        case FATURATARIHIBASLANGIC:
            return getFaturaTarihiBaslangic();
        case FATURATARIHIBITIS:
            return getFaturaTarihiBitis();
        case STATUS:
            return getStatus();
        case FATURAGONDERIMBASLANGIC:
            return getFaturaGonderimBaslangic();
        case FATURAGONDERIMBITIS:
            return getFaturaGonderimBitis();
        case SOURCE:
            return getSource();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EARSIVNO:
            setEArsivNo((String)value);
            return;
        case TCKNVKN:
            setTcknVkn((String)value);
            return;
        case FIRMAADI:
            setFirmaAdi((String)value);
            return;
        case FATURATARIHIBASLANGIC:
            setFaturaTarihiBaslangic((Date)value);
            return;
        case FATURATARIHIBITIS:
            setFaturaTarihiBitis((Date)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case FATURAGONDERIMBASLANGIC:
            setFaturaGonderimBaslangic((Date)value);
            return;
        case FATURAGONDERIMBITIS:
            setFaturaGonderimBitis((Date)value);
            return;
        case SOURCE:
            setSource((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Source
     */
    public String getSource() {
        return (String) getAttributeInternal(SOURCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Source
     */
    public void setSource(String value) {
        setAttributeInternal(SOURCE, value);
    }
}
