package xxxt.oracle.apps.xxxt.einvoice.earchive.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EArchiveHeaderVORowImpl extends OAViewRowImpl {
    public static final int EINVINVOICEID = 0;
    public static final int ORGANIZATIONNAME = 1;
    public static final int INTERNALSOURCE = 2;
    public static final int INVOICEID = 3;
    public static final int INVOICEDATE = 4;
    public static final int SENTDATE = 5;
    public static final int TAXREGNUMBER = 6;
    public static final int VENDORCUSTOMERNAME = 7;
    public static final int VENDORCUSTOMERSITE = 8;
    public static final int PAYABLECURRENCY = 9;
    public static final int PAYABLEAMOUNT = 10;
    public static final int EMAIL = 11;
    public static final int STATUSID = 12;
    public static final int STATUSNAME = 13;
    public static final int DETAILFLAG = 14;
    public static final int SELECTEDFLAG = 15;
    public static final int SELECTSWITCHER = 16;
    public static final int COLORSWITCHER = 17;
    public static final int EARCHIVELINESVO = 18;
    public static final int EARCHIVENOTESVO = 19;

    /**This is the default constructor (do not remove)
     */
    public EArchiveHeaderVORowImpl() {
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link EArchiveLinesVO
     */
    public RowIterator getEArchiveLinesVO() {
        return (RowIterator)getAttributeInternal(EARCHIVELINESVO);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link EArchiveNotesVO
     */
    public RowIterator getEArchiveNotesVO() {
        return (RowIterator)getAttributeInternal(EARCHIVENOTESVO);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EINVINVOICEID:
            return getEinvInvoiceId();
        case ORGANIZATIONNAME:
            return getOrganizationName();
        case INTERNALSOURCE:
            return getInternalSource();
        case INVOICEID:
            return getInvoiceId();
        case INVOICEDATE:
            return getInvoiceDate();
        case SENTDATE:
            return getSentDate();
        case TAXREGNUMBER:
            return getTaxRegNumber();
        case VENDORCUSTOMERNAME:
            return getVendorCustomerName();
        case VENDORCUSTOMERSITE:
            return getVendorCustomerSite();
        case PAYABLECURRENCY:
            return getPayableCurrency();
        case PAYABLEAMOUNT:
            return getPayableAmount();
        case EMAIL:
            return getEmail();
        case STATUSID:
            return getStatusId();
        case STATUSNAME:
            return getStatusName();
        case DETAILFLAG:
            return getDetailFlag();
        case SELECTEDFLAG:
            return getSelectedFlag();
        case SELECTSWITCHER:
            return getSelectSwitcher();
        case COLORSWITCHER:
            return getColorSwitcher();
        case EARCHIVELINESVO:
            return getEArchiveLinesVO();
        case EARCHIVENOTESVO:
            return getEArchiveNotesVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EINVINVOICEID:
            setEinvInvoiceId((Number)value);
            return;
        case ORGANIZATIONNAME:
            setOrganizationName((String)value);
            return;
        case INTERNALSOURCE:
            setInternalSource((String)value);
            return;
        case INVOICEID:
            setInvoiceId((String)value);
            return;
        case INVOICEDATE:
            setInvoiceDate((Date)value);
            return;
        case SENTDATE:
            setSentDate((Date)value);
            return;
        case TAXREGNUMBER:
            setTaxRegNumber((String)value);
            return;
        case VENDORCUSTOMERNAME:
            setVendorCustomerName((String)value);
            return;
        case VENDORCUSTOMERSITE:
            setVendorCustomerSite((String)value);
            return;
        case PAYABLECURRENCY:
            setPayableCurrency((String)value);
            return;
        case PAYABLEAMOUNT:
            setPayableAmount((Number)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case STATUSID:
            setStatusId((Number)value);
            return;
        case STATUSNAME:
            setStatusName((String)value);
            return;
        case DETAILFLAG:
            setDetailFlag((Boolean)value);
            return;
        case SELECTEDFLAG:
            setSelectedFlag((String)value);
            return;
        case SELECTSWITCHER:
            setSelectSwitcher((String)value);
            return;
        case COLORSWITCHER:
            setColorSwitcher((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute EinvInvoiceId
     */
    public Number getEinvInvoiceId() {
        return (Number) getAttributeInternal(EINVINVOICEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EinvInvoiceId
     */
    public void setEinvInvoiceId(Number value) {
        setAttributeInternal(EINVINVOICEID, value);
    }

    /**Gets the attribute value for the calculated attribute OrganizationName
     */
    public String getOrganizationName() {
        return (String) getAttributeInternal(ORGANIZATIONNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationName
     */
    public void setOrganizationName(String value) {
        setAttributeInternal(ORGANIZATIONNAME, value);
    }

    /**Gets the attribute value for the calculated attribute InternalSource
     */
    public String getInternalSource() {
        return (String) getAttributeInternal(INTERNALSOURCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InternalSource
     */
    public void setInternalSource(String value) {
        setAttributeInternal(INTERNALSOURCE, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceId
     */
    public String getInvoiceId() {
        return (String) getAttributeInternal(INVOICEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceId
     */
    public void setInvoiceId(String value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute SentDate
     */
    public Date getSentDate() {
        return (Date) getAttributeInternal(SENTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SentDate
     */
    public void setSentDate(Date value) {
        setAttributeInternal(SENTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute TaxRegNumber
     */
    public String getTaxRegNumber() {
        return (String) getAttributeInternal(TAXREGNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TaxRegNumber
     */
    public void setTaxRegNumber(String value) {
        setAttributeInternal(TAXREGNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute VendorCustomerName
     */
    public String getVendorCustomerName() {
        return (String) getAttributeInternal(VENDORCUSTOMERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorCustomerName
     */
    public void setVendorCustomerName(String value) {
        setAttributeInternal(VENDORCUSTOMERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute VendorCustomerSite
     */
    public String getVendorCustomerSite() {
        return (String) getAttributeInternal(VENDORCUSTOMERSITE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VendorCustomerSite
     */
    public void setVendorCustomerSite(String value) {
        setAttributeInternal(VENDORCUSTOMERSITE, value);
    }

    /**Gets the attribute value for the calculated attribute PayableCurrency
     */
    public String getPayableCurrency() {
        return (String) getAttributeInternal(PAYABLECURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PayableCurrency
     */
    public void setPayableCurrency(String value) {
        setAttributeInternal(PAYABLECURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute PayableAmount
     */
    public Number getPayableAmount() {
        return (Number) getAttributeInternal(PAYABLEAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PayableAmount
     */
    public void setPayableAmount(Number value) {
        setAttributeInternal(PAYABLEAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for the calculated attribute StatusId
     */
    public Number getStatusId() {
        return (Number) getAttributeInternal(STATUSID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusId
     */
    public void setStatusId(Number value) {
        setAttributeInternal(STATUSID, value);
    }

    /**Gets the attribute value for the calculated attribute StatusName
     */
    public String getStatusName() {
        return (String) getAttributeInternal(STATUSNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusName
     */
    public void setStatusName(String value) {
        setAttributeInternal(STATUSNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DetailFlag
     */
    public Boolean getDetailFlag() {
        return (Boolean) getAttributeInternal(DETAILFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DetailFlag
     */
    public void setDetailFlag(Boolean value) {
        setAttributeInternal(DETAILFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute SelectedFlag
     */
    public String getSelectedFlag() {
        return (String) getAttributeInternal(SELECTEDFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectedFlag
     */
    public void setSelectedFlag(String value) {
        setAttributeInternal(SELECTEDFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute SelectSwitcher
     */
    public String getSelectSwitcher() {
        return (String) getAttributeInternal(SELECTSWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectSwitcher
     */
    public void setSelectSwitcher(String value) {
        setAttributeInternal(SELECTSWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute ColorSwitcher
     */
    public String getColorSwitcher() {
        return (String) getAttributeInternal(COLORSWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ColorSwitcher
     */
    public void setColorSwitcher(String value) {
        setAttributeInternal(COLORSWITCHER, value);
    }
}
