package xxxt.oracle.apps.xxxt.einvoice.earchive.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EArchiveSourcesVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public EArchiveSourcesVOImpl() {
    }
}
